<?php

// Wie config/messages/de: "Space" heisst bei N.E.X.U.S. "Kreis" (Josh, 25.09.2026).
return array (
  '<b>This space is still empty!</b>' => '<b>¡Este círculo todavía está vacío!</b>',
  '<b>This space is still empty!</b><br>Start by posting something here...' => '<b>¡Este círculo está aun vacio!</b><br>Empieza por escribir algo aqui...',
  '<b>You are not member of this space and there is no public content, yet!</b>' => '<b>No eres miembro de este círculo y no hay contenido público aún!</b>',
  '<strong>About</strong> the Space' => '<strong>Sobre</strong> este Círculo',
  '<strong>Leave</strong> Space' => '<strong>Abandonar</strong> este círculo',
  '<strong>New</strong> spaces' => '<strong>Nuevos</strong> círculos',
  '<strong>Request</strong> Membership' => '<strong>Solicitar</strong> suscripción al círculo',
  '<strong>Space</strong> followers' => 'Seguidores del <strong>Círculo</strong>',
  '<strong>Space</strong> members' => 'Miembros del <strong>círculo</strong>',
  '<strong>Space</strong> menu' => 'Menú <strong>círculo</strong>',
  '<strong>Space</strong> tags' => 'Etiquetas de <strong>Círculo</strong>',
  '<strong>Spaces</strong>' => '<strong>Círculos</strong>',
  'Access to this Space is restricted. Please introduce yourself to become a member.' => 'Por favor, preséntate brevemente, para ser un miembro aprobado de este círculo.',
  'Add as Default Space for new users' => 'Añadir como círculo por defecto para los nuevos usuarios',
  'Advanced Spaces Search' => 'Búsqueda avanzada en los círculos',
  'As owner you cannot revoke your membership!' => '¡Como propietario no puedes revocar tu suscripción!',
  'Find Spaces by their description or by their tags' => 'Encontrar círculos por su descripción o por su etiquetas',
  'My Space List' => 'Mi lista de círculos',
  'My space summary' => 'Mi resumen del círculo',
  'No spaces found.' => 'No se encontraron Círculos',
  'Sorry, you are not allowed to leave this space!' => 'Lo sentimos, no tienes permitido dejar este círculo!',
  'Space' => 'Círculo',
  'Space Name' => 'Nombre del círculo',
  'Space Visibility' => 'Visibilidad de este círculo',
  'Space directory' => 'Directorio de círculos',
  'Space is invisible!' => '¡El círculo es invisible!',
  'Spaces' => 'Círculos',
  'The default homepage for members of this Space' => 'Página de inicio por defecto para los miembros de este Círculo',
  'The default homepage for non-members and guests visiting this Space' => 'Página de inicio por defecto para no miembros e invitados que visitan este Círculo',
  'This action is only available for workspace members!' => '¡Esta acción solo está disponible para miembros del círculo!',
  'This user is already a member of this space.' => 'Este usuario ya es miembro de este círculo.',
  'This user is not a member of this space.' => 'Este usuario no es miembro de este círculo.',
  'To invite users to this space, please type their names below to find and pick them.' => 'Para invitar usuarios a este círculo, por favor escribe sus nombres debajo para encontrarlos y escogerlos.',
  'User \'{username}\' is already a member of this space!' => 'El usuario \'{username}\' ya es miembro de este círculo!',
  'Warning: If you change the visibility settings of a Space from public to private, all content within that Space, including posts, comments, attachments etc. will also be set to private. This means that non-members will no longer be able to see, access, or interact with any of the content within that Space.' => 'Atención: Si cambia la configuración de visibilidad del círculo de público a privado, todo el contenido del círculo, incluyendo las publicaciones, los archivos vinculados, etc., serán también considerados privados. Esto significa que los no miembros ya no podrán ver, acceder o interactuar con ningún contenido de este círculo.',
  'Would you like to end your membership in Space {spaceName}?' => '¿Quieres dar por terminada tu pertenencia al Círculo {spaceName}?',
  'Would you like to unfollow Space {spaceName}?' => '¿Quieres dejar de seguir el Círculo {spaceName}?',
  'Would you like to withdraw your request to join Space {spaceName}?' => '¿Quieres retirar tu solicitud de pertenencia al Círculo {spaceName}?',
  'You are not allowed to join this space!' => '¡No puedes unirte a este círculo!',
  'You cannot create private visible spaces!' => '¡No puedes crear círculos privados visibles!',
  'You cannot create public visible spaces!' => '¡No puedes crear círculos públicos visibles!',
  'You need to login to view contents of this space!' => '¡Necesitas iniciar sesión para ver los contenidos de este círculo!',
  'Your request was successfully submitted to the space administrators.' => 'Tu solicitud ha sido enviada correctamente a los administradores del círculo.',
);
