<?php

// Wie config/messages/de: "Space" heisst bei N.E.X.U.S. "Kreis" (Josh, 25.09.2026).
return array (
  '<b>This space is still empty!</b>' => '<b>This circle is still empty!</b>',
  '<b>This space is still empty!</b><br>Start by posting something here...' => '<b>This circle is still empty!</b><br>Start by posting something here...',
  '<b>You are not member of this space and there is no public content, yet!</b>' => '<b>You are not member of this circle and there is no public content, yet!</b>',
  '<strong>About</strong> the Space' => '<strong>About</strong> the Circle',
  '<strong>Leave</strong> Space' => '<strong>Leave</strong> Circle',
  '<strong>New</strong> spaces' => '<strong>New</strong> circles',
  '<strong>Request</strong> Membership' => '<strong>Request</strong> Membership',
  '<strong>Space</strong> followers' => '<strong>Circle</strong> followers',
  '<strong>Space</strong> members' => '<strong>Circle</strong> members',
  '<strong>Space</strong> menu' => '<strong>Circle</strong> menu',
  '<strong>Space</strong> tags' => '<strong>Circle</strong> tags',
  '<strong>Spaces</strong>' => '<strong>Circles</strong>',
  'Access to this Space is restricted. Please introduce yourself to become a member.' => 'Access to this Circle is restricted. Please introduce yourself to become a member.',
  'Add as Default Space for new users' => 'Add as Default Circle for new users',
  'Advanced Spaces Search' => 'Advanced Circles Search',
  'As owner you cannot revoke your membership!' => 'As owner you cannot revoke your membership!',
  'Find Spaces by their description or by their tags' => 'Find Circles by their description or by their tags',
  'My Space List' => 'My Circle List',
  'My space summary' => 'My circle summary',
  'No spaces found.' => 'No circles found.',
  'Sorry, you are not allowed to leave this space!' => 'Sorry, you are not allowed to leave this circle!',
  'Space' => 'Circle',
  'Space Name' => 'Circle Name',
  'Space Visibility' => 'Circle Visibility',
  'Space directory' => 'Circle directory',
  'Space is invisible!' => 'Circle is invisible!',
  'Spaces' => 'Circles',
  'The default homepage for members of this Space' => 'The default homepage for members of this Circle',
  'The default homepage for non-members and guests visiting this Space' => 'The default homepage for non-members and guests visiting this Circle',
  'This action is only available for workspace members!' => 'This action is only available for workcircle members!',
  'This user is already a member of this space.' => 'This user is already a member of this circle.',
  'This user is not a member of this space.' => 'This user is not a member of this circle.',
  'To invite users to this space, please type their names below to find and pick them.' => 'To invite users to this circle, please type their names below to find and pick them.',
  'User \'{username}\' is already a member of this space!' => 'User \'{username}\' is already a member of this circle!',
  'Warning: If you change the visibility settings of a Space from public to private, all content within that Space, including posts, comments, attachments etc. will also be set to private. This means that non-members will no longer be able to see, access, or interact with any of the content within that Space.' => 'Warning: If you change the visibility settings of a Circle from public to private, all content within that Circle, including posts, comments, attachments etc. will also be set to private. This means that non-members will no longer be able to see, access, or interact with any of the content within that Circle.',
  'Would you like to end your membership in Space {spaceName}?' => 'Would you like to end your membership in Circle {spaceName}?',
  'Would you like to unfollow Space {spaceName}?' => 'Would you like to unfollow Circle {spaceName}?',
  'Would you like to withdraw your request to join Space {spaceName}?' => 'Would you like to withdraw your request to join Circle {spaceName}?',
  'You are not allowed to join this space!' => 'You are not allowed to join this circle!',
  'You cannot create private visible spaces!' => 'You cannot create private visible circles!',
  'You cannot create public visible spaces!' => 'You cannot create public visible circles!',
  'You need to login to view contents of this space!' => 'You need to login to view contents of this circle!',
  'Your request was successfully submitted to the space administrators.' => 'Your request was successfully submitted to the circle administrators.',
);
