<?php

return array (
  '<b>This space is still empty!</b>' => '<b>Dieser Kreis ist noch leer!</b>',
  '<b>This space is still empty!</b><br>Start by posting something here...' => '<strong>Dieser Kreis ist noch leer!</strong><br />Mache den Anfang und teile etwas mit ...',
  '<b>You are not member of this space and there is no public content, yet!</b>' => '<b>Du bist noch kein Mitglied dieses Kreises. Derzeit liegen keinen öffentlichen Inhalte vor!</b>',
  '<strong>About</strong> the Space' => '<strong>Über</strong> diesen Kreis',
  '<strong>Leave</strong> Space' => 'Kreis <strong>verlassen</strong>',
  '<strong>New</strong> spaces' => '<strong>Neue</strong> Kreise',
  '<strong>Request</strong> Membership' => 'Kreis-Mitgliedschaft <strong>beantragen</strong>',
  '<strong>Space</strong> followers' => '<strong>Kreis</strong>-Follower',
  '<strong>Space</strong> members' => '<strong>Kreis</strong>-Mitglieder',
  '<strong>Space</strong> menu' => '<strong>Kreis</strong>-Menü',
  '<strong>Space</strong> tags' => '<strong>Kreis</strong> tags',
  '<strong>Spaces</strong>' => '<strong>Kreise</strong>',
  'Access to this Space is restricted. Please introduce yourself to become a member.' => 'Um bestätigtes Mitglied dieses Kreises zu werden, stelle dich bitte kurz vor.',
  'Add as Default Space for new users' => 'Als Standard-Kreis für neue Benutzer hinzufügen',
  'Advanced Spaces Search' => 'Erweiterte Kreis-Suche',
  'As owner you cannot revoke your membership!' => 'Als Eigentümer des Kreises kannst du deine Mitgliedschaft nicht beenden!',
  'Find Spaces by their description or by their tags' => 'Finde Kreise anhand Ihrer Beschreibung oder anhand Ihrer "Tags"',
  'My Space List' => 'Meine Kreise',
  'My space summary' => 'Meine Kreis-Zusammenfassung',
  'No spaces found.' => 'Keine Kreise gefunden.',
  'Sorry, you are not allowed to leave this space!' => 'Sorry, aber du kannst diesen Kreis nicht verlassen.',
  'Space' => 'Kreis',
  'Space Name' => 'Name des Kreises',
  'Space Visibility' => 'Kreis Sichtbarkeit',
  'Space directory' => 'Kreis-Verzeichnis',
  'Space is invisible!' => 'Kreis ist unsichtbar!',
  'Spaces' => 'Kreise',
  'The default homepage for members of this Space' => 'Die Homepage für Mitglieder dieses Kreises.',
  'The default homepage for non-members and guests visiting this Space' => 'Die Homepage für Nicht-Mitglieder dieses Kreises und Gäste.',
  'This action is only available for workspace members!' => 'Diese Aktion ist nur für Kreis-Mitglieder verfügbar!',
  'This user is already a member of this space.' => 'Dieser Benutzer ist bereits Miglied dieses Kreis.',
  'This user is not a member of this space.' => 'Dieser Benutzer ist kein Mitglied dieses Kreis.',
  'To invite users to this space, please type their names below to find and pick them.' => 'Um Benutzer in diesen Kreis einzuladen, gib deren Name unten ein, um sie zu suchen und auszuwählen.',
  'User \'{username}\' is already a member of this space!' => 'Der Benutzer \'{username}\' ist bereits Mitglied des Kreises!',
  'Warning: If you change the visibility settings of a Space from public to private, all content within that Space, including posts, comments, attachments etc. will also be set to private. This means that non-members will no longer be able to see, access, or interact with any of the content within that Space.' => 'Warnung: Wenn du die Sichtbarkeitseinstellungen eines Kreises von "Öffentlich" auf "Privat" änderst, werden alle Inhalte in diesem Kreis, einschließlich Beiträge, Kommentare, Anhänge usw., ebenfalls privat. Das bedeutet, dass Nicht-Mitglieder die Inhalte in diesem Bereich nicht mehr sehen, darauf zugreifen oder damit interagieren können.',
  'Would you like to end your membership in Space {spaceName}?' => 'Möchtest du deine Mitgliedschaft in dem Kreis {spaceName} wirklich beenden?',
  'Would you like to unfollow Space {spaceName}?' => 'Möchtest du dem Kreis {spaceName} wirklich aufhören zu folgen?',
  'Would you like to withdraw your request to join Space {spaceName}?' => 'Möchtest du deine Anfrage dem Kreis {spaceName} beizutreten wirklich zurückziehen?',
  'You are not allowed to join this space!' => 'Du darfst diesem Kreis nicht betreten!',
  'You cannot create private visible spaces!' => 'Du kannst keine privaten Kreise erstellen!',
  'You cannot create public visible spaces!' => 'Du kannst keine öffentlichen Kreise erstellen!',
  'You need to login to view contents of this space!' => 'Du musst dich einloggen, um die Inhalte dieses Kreises sehen zu können!',
  'Your request was successfully submitted to the space administrators.' => 'Deine Anfrage wurde erfolgreich an die Kreis-Administratoren weitergeleitet.',
);
